### ISSUE TITLE
Hidden ENV variable  FS_API_PORT needs to be documented …

### ISSUE THREAD

**Issue by duncdrum** [evolvedbinary/fusion-studio-api#36]
Or even better drop Env variables all together, there is no reason to require the same info once as ENV variable and then again as system variable. 

[the source of much troubble](https://github.com/evolvedbinary/fusion-studio-api/blob/f0ba6acdf9a760c8d28dc09b9aed9413b4921006/src/test/java/com/fusiondb/studio/api/API.java#L62)

**Comment by adamretter** [comment]
1. I agree there should be only one setting
2. It should work out-of-the-box with FusionDB nightly

**Comment by adamretter** [comment]
At the moment, I can confirm that `mvn verify` works out of the box on a clean machine.
The only prerequisite is to add the auth for the Docker repo details to your `~/.m2/settings.xml`, i.e.:

```xml
<server>
      <id>repo.evolvedbinary.com:9543</id>
      <username>your-username</username>
      <password>your-password</password>
</server>
```

---
Another option instead of editing `~/.m2/settings.xml` is to pass them at runtime, e.g. `mvn verify -Ddocker.username=your-username -Ddocker.password=your-password`

**Comment by duncdrum** [comment]
@adamretter this info is part of #35, on clean system the command will work for either alpha or nightly not both,

**Comment by adamretter** [comment]
You can test against any image (both nightly and alpha), you just have to set the appropriate system properties. I am updating the README.md.
